### ISSUE TITLE
about training code ?

### ISSUE THREAD

**Issue by pokameng** [UCSC-VLAA/story-adapter#1]
@jwmao1 @xk-huang @yunfeixie233 
great work！！！
I am now working on the consistency loss, and also thinking about how to use the image obtained in the previous step as a reference image for the next time.

Your work is great. It seems to me that this will be used in multiple tasks.

I would like to know if the training code will be released?

**Comment by jwmao1** [comment]
Thank you very much for your interest in our work. Story-Adapter is a training-free story visualization framework, so we didn't include any training code. Since the attention weights depend on the inputs, our proposed global reference cross-attention has the opportunity to follow the weights of the existing diffusion model to aggregate information flow from all generated images from the previous iteration for current image generation without training. Hope this helps and thanks again for your interest.

**Comment by pokameng** [comment]
ok thanks！Got it！！！


繁华落尽
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jwmao1/story-adapter"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月14日(星期一) 下午2:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jwmao1/story-adapter] about training code ? (Issue #1)





 
Thank you very much for your interest in our work. Story-Adapter is a training-free story visualization framework, so we didn't include any training code. Since the attention weights depend on the inputs, our proposed global reference cross-attention has the opportunity to follow the weights of the existing diffusion model to aggregate information flow from all generated images from the previous iteration for current image generation without training. Hope this helps and thanks again for your interest.
