### ISSUE TITLE
Dataset for Long Story Visualization

### ISSUE THREAD

**Issue by asdjia** [UCSC-VLAA/story-adapter#4]
Hi,

Thank you for your excellent work. May I kindly ask if you could provide the long story visualization dataset used in the paper?

Thank you.

**Comment by jwmao1** [comment]
Thank you for your question. Since Story-Adapter is training-free, we do not have a corresponding long story visualization dataset; instead, we have designed long story cases for evaluation. Some examples are provided in `run.py` (https://github.com/jwmao1/story-adapter/blob/3c66de4d2bcb30d7480faf6180d9bcac31642b78/run.py#L12C1-L485C2).
If our paper can be accepted, we will consider publishing additional cases. Thank you again for your attention to our work.

**Comment by asdjia** [comment]
Hi, I still have one question—sorry to bother you. As mentioned in the paper, you used aFID and aCCS for evaluation.

Do these metrics compute comparisons between the reference images and the generated images? If so, may I ask which reference images were used, considering there are multiple iterations?

Thank you for your time!

**Comment by jwmao1** [comment]
Thank you for your question. Regarding the aFID and aCCS evaluations, we first cropped out the regions of the same character in the story sequence using Grounding DINO, and used the first cropped image as a reference to compute the metrics between the rest of the cropped images and that reference image.
